$background = rgb(040010)
$foreground = rgb(FFFAE3)
$color0 = rgb(040010)
$color1 = rgb(FC97A7)
$color2 = rgb(01D1F7)
$color3 = rgb(A0C8BF)
$color4 = rgb(FEB6F8)
$color5 = rgb(FDD7C4)
$color6 = rgb(FFF0AF)
$color7 = rgb(F6EFCE)
$color8 = rgb(ADA791)
$color9 = rgb(FC97A7)
$color10 = rgb(01D1F7)
$color11 = rgb(A0C8BF)
$color12 = rgb(FEB6F8)
$color13 = rgb(FDD7C4)
$color14 = rgb(FFF0AF)
$color15 = rgb(F6EFCE)
