font_family     JetBrainsMono NF SemiBold
font_size 	    12.0
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto

confirm_os_window_close 0

foreground         #FFFAE3
background         #040010
background_opacity 0.7
cursor             #80E5ED

selection_foreground #000000
selection_background #F5FBFF

active_tab_foreground     #040010
active_tab_background     #FFFAE3
inactive_tab_foreground   #FFFAE3
inactive_tab_background   #040010

active_border_color   #FFFAE3
inactive_border_color #040010
bell_border_color     #FC97A7

color0      #040010
color1		#FC97A7
color2		#01D1F7
color3		#A0C8BF
color4		#FEB6F8
color5		#FDD7C4
color6		#FFF0AF
color7		#F6EFCE
color8		#ADA791
color9		#FC97A7
color10		#01D1F7
color11		#A0C8BF
color12		#FEB6F8
color13		#FDD7C4
color14		#FFF0AF
color15		#F6EFCE
